### ISSUE TITLE
Common Annotations are not applied to pods

### ISSUE THREAD

**Issue by ubajze** [nautobot/helm-charts#108]
I added the value for `commonAnnotations`, but the value is not applied to my pods.

```
apiVersion: v1
data:
  values: |
    ---
    commonAnnotations:
      reloader.stakater.com/auto: "true"
```

```
$ k get pods nautobot-5478658bc6-m8l8l -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2022-01-05T09:40:58Z"
```
