### ISSUE TITLE
Add observability for celery workers

### ISSUE THREAD

**Issue by mundruid** [nautobot/helm-charts#191]
Environment

    Nautobot version: ^1.3

Proposed Functionality

Nautobot has changed to use celery workers instead of rq workers, therefore we need to enable task monitoring by using a specific option `-E` when we start the celery worker, in order to observe tasks in the redis queue that the celery worker is using. The following code is the way can do this in `docker-compose.yml`:
```yaml
  celery:
    entrypoint: "nautobot-server celery worker -l INFO -E"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base
```

Then in the celery worker logs you will observe that task events are on:
```
-- ******* ---- Linux-4.19.0-18-amd64-x86_64-with-debian-11.3 2022-06-30 12:48:17
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         nautobot:0x7f7d359bb6d0
- ** ---------- .> transport:   redis://:**@redis:6379/0
- ** ---------- .> results:     redis://:**@redis:6379/0
- *** --- * --- .> concurrency: 24 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
```
