### ISSUE TITLE
Allow additionalParameters

### ISSUE THREAD

**Issue by blackpioter** [nautobot/helm-charts#214]
While using Skaffold Helm deployment, secrets encrypted via sops are not allowed due to `additionalProperties: false`.

```
ERRO[0014] Error: values don't meet the specifications of the schema(s) in the following chart(s):
nautobot:
- (root): Additional property sops is not allowed
  subtask=0 task=Render
std out err: %!(EXTRA *errors.errorString=Error: values don't meet the specifications of the schema(s) in the following chart(s):
nautobot:
- (root): Additional property sops is not allowed

)

```
To solve this please allow additionalProperties: https://github.com/nautobot/helm-charts/blob/v1.3.13/charts/nautobot/values.schema.json#L363

**Comment by nniehoff** [comment]
@blackpioter thanks for opening this issue, I'd like to get this addressed quickly.  I'm not familiar with how skaffold works and I'm only somewhat familiary with mozilla sops.  Is it the sops requirement that is adding the `sops` property or is it skaffold?

**Comment by blackpioter** [comment]
@nniehoff it is sops requirement. The values file that contains secrets has an additional root structure `sops:` that provides details on where does the encryption keys come from.

Example:
```

nautobot:
    secretKey: ENC[redacted]
    superUser:
        apiToken: ENC[redacted]
        password: ENC[redacted]
sops:
    kms: (...)

```
