### ISSUE TITLE
v2.0.0 does not allow KV nodeSelector.

### ISSUE THREAD

**Issue by iodeslykos** [nautobot/helm-charts#256]
When attempting to upgrade to v2.0.0, values that had worked previously are failing schema validation. In our case it's  `nodeSelector:` where the key "environment" in the label is rejected.

When deploying via Terraform:

```
Error: malformed chart or values: 
	values.yaml: 
- celeryBeat.nodeSelector: Must validate one and only one schema (oneOf)
- celeryBeat.nodeSelector: Additional property environment is not allowed
- celeryBeat: Must validate all the schemas (allOf)
- celeryBeat: Must validate all the schemas (allOf)
- celeryWorker.nodeSelector: Must validate one and only one schema (oneOf)
- celeryWorker.nodeSelector: Additional property environment is not allowed
- celeryWorker: Must validate all the schemas (allOf)
- celeryWorker: Must validate all the schemas (allOf)
- nautobot.nodeSelector: Must validate one and only one schema (oneOf)
- nautobot.nodeSelector: Additional property environment is not allowed
- nautobot: Must validate all the schemas (allOf)
- nautobot: Must validate all the schemas (allOf)
```

Failing values:

```
nautobot:
  nodeSelector: { environment: ${var.node_selector} }
celeryWorker:
  nodeSelector: { environment: ${var.node_selector} }
celeryBeat:
  nodeSelector: { environment: ${var.node_selector} }
```
