### ISSUE TITLE
Add ability to provide secretKey via reference

### ISSUE THREAD

**Issue by BlackDark** [nautobot/helm-charts#283]
Currently only directly supported via setting plain value in values file.

**Comment by BlackDark** [comment]
Yes,  similar to the db password etc.

```yml
nautobot:
	secretKey:
		existingSecret: name-of-secret
		existingSecretKey: key

# currently only this option works
nautobot:
	secretKey: blablamagicsecret
# could go via sops and encrypt the file / value but why not using existing kubernetes features
```
