### ISSUE TITLE
Nautobot init container failing due to "sed: cannot rename /opt/nautobot/sedhsv1Fo: Device or resource busy"

### ISSUE THREAD

**Issue by slbyrnes1** [nautobot/helm-charts#284]
# Issue

Hi all!

I am running into an issue where the Nautobot init container consistently fails with errors like "sed: cannot rename /opt/nautobot/sedhsv1Fo: Device or resource busy" after echoing superuser information.

I suspect it is an issue with writing to /opt/nautobot/uwsgi.ini with sed during Nautobot's [docker-entrypoint](https://github.com/nautobot/nautobot/blob/496ce1000c8c5cb5962dbd58ca2ed190fbeaf028/docker/docker-entrypoint.sh#LL92C1-L92C1).

**Helm version**: 2.0.2
**Tested with Nautobot**:
- 1.5.17-py3.10
- 1.5.20-py3.10
- v2.0.0-alpha.3-py3.10

## Debug Output

Excerpt from the `nautobot-init` container logs before it terminates.

```
nautobot-init Found no missing power port paths; skipping
nautobot-init Finished.
nautobot-init 
nautobot-init Collecting static files...
nautobot-init 
nautobot-init 0 static files copied to '/opt/nautobot/static', 714 unmodified.
nautobot-init 
nautobot-init Removing stale content types...
nautobot-init 
nautobot-init Removing expired sessions...
nautobot-init 
nautobot-init ⏳ Running initial systems check...
nautobot-init System check identified some issues:
nautobot-init 
nautobot-init WARNINGS:
nautobot-init ?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
nautobot-init ?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
nautobot-init ?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
nautobot-init ?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
nautobot-init ?: (security.W018) You should not have DEBUG set to True in deployment.
nautobot-init 
nautobot-init System check identified 5 issues (0 silenced).
nautobot-init 💡 Superuser Username: admin, E-Mail: <redacted>
nautobot-init sed: cannot rename /opt/nautobot/sedhsv1Fo: Device or resource busy
Stream closed EOF for mesa-dev-nautobot/nautobot-default-7b85d4d888-9pf7c (nautobot-init)
```

#### Describe Pod

```
Name:         nautobot-default-7b85d4d888-9pf7c
Namespace:    mesa-dev-nautobot
Priority:     0
Node:         <redacted>
Start Time:   Tue, 06 Jun 2023 08:37:35 -0700
Labels:       app.kubernetes.io/component=nautobot-default
              app.kubernetes.io/instance=nautobot
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=nautobot
              helm.sh/chart=nautobot-2.0.2
              pod-template-hash=7b85d4d888
Annotations:  <none>
Status:       Pending
IP:           10.42.1.30
IPs:
  IP:           10.42.1.30
Controlled By:  ReplicaSet/nautobot-default-7b85d4d888
Init Containers:
  nautobot-init:
    Container ID:  containerd://669cc7f3bb5df7903b1e694ea18dba12dee2634aede70159c9ac0c2f6d80d5b5
    Image:         ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
    Image ID:      ghcr.io/nautobot/nautobot@sha256:ea07002d065471f7e5fa4bf1aa3d17bdb026daabbfde6084949489e1f9ef48ed
    Port:          <none>
    Host Port:     <none>
    Args:
      echo
      Nautobot Initialization Done
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    4
      Started:      Tue, 06 Jun 2023 09:26:28 -0700
      Finished:     Tue, 06 Jun 2023 09:26:52 -0700
    Ready:          False
    Restart Count:  13
    Limits:
      cpu:     600m
      memory:  8704M
    Requests:
      cpu:     100m
      memory:  1280M
    Environment Variables from:
      nautobot-env           ConfigMap  Optional: false
      nautobot-env           Secret     Optional: false
      mesa-nautobot-secrets  Secret     Optional: false
    Environment:
      NAUTOBOT_UWSGI_BUFFER_SIZE:  8192
    Mounts:
      /opt/nautobot/git from git-repos (rw)
      /opt/nautobot/static from nautobot-static (rw)
      /opt/nautobot/uwsgi.ini from nautobot-config (rw,path="uwsgi.ini")
Containers:
  nautobot:
    Container ID:  
    Image:         ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
    Image ID:      
    Ports:         8443/TCP, 8080/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      nautobot-server
      start
      --ini
      /opt/nautobot/uwsgi.ini
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     600m
      memory:  8704M
    Requests:
      cpu:      100m
      memory:   1280M
    Liveness:   http-get http://:http/api/ delay=3s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/health/ delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment Variables from:
      nautobot-env           ConfigMap  Optional: false
      nautobot-env           Secret     Optional: false
      mesa-nautobot-secrets  Secret     Optional: false
    Environment:
      NAUTOBOT_K8S_COMPONENT:                              nautobot-default
      NAUTOBOT_UWSGI_BUFFER_SIZE:                          8192
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          kdev
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        mesa-dev-nautobot (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              nautobot-default-7b85d4d888-9pf7c (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        nautobot
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
      NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME:       nautobot-default
    Mounts:
      /opt/nautobot/git from git-repos (rw)
      /opt/nautobot/static from nautobot-static (rw)
      /opt/nautobot/uwsgi.ini from nautobot-config (rw,path="uwsgi.ini")
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nautobot-static:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  git-repos:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  nautobot-config:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        nautobot-config
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  51m                   default-scheduler  Successfully assigned mesa-dev-nautobot/nautobot-default-7b85d4d888-9pf7c to kdev-compute-1
  Normal   Pulled     46m (x5 over 51m)     kubelet            Container image "ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10" already present on machine
  Normal   Created    46m (x5 over 51m)     kubelet            Created container nautobot-init
  Normal   Started    46m (x5 over 51m)     kubelet            Started container nautobot-init
  Warning  BackOff    102s (x196 over 48m)  kubelet            Back-off restarting failed container
Name:         nautobot-default-7b85d4d888-9pf7c
Namespace:    mesa-dev-nautobot
Priority:     0
Node:         <redacted>
Start Time:   Tue, 06 Jun 2023 08:37:35 -0700
Labels:       app.kubernetes.io/component=nautobot-default
              app.kubernetes.io/instance=nautobot
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=nautobot
              helm.sh/chart=nautobot-2.0.2
              pod-template-hash=7b85d4d888
Annotations:  <none>
Status:       Pending
IP:           10.42.1.30
IPs:
  IP:           10.42.1.30
Controlled By:  ReplicaSet/nautobot-default-7b85d4d888
Init Containers:
  nautobot-init:
    Container ID:  containerd://669cc7f3bb5df7903b1e694ea18dba12dee2634aede70159c9ac0c2f6d80d5b5
    Image:         ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
    Image ID:      ghcr.io/nautobot/nautobot@sha256:ea07002d065471f7e5fa4bf1aa3d17bdb026daabbfde6084949489e1f9ef48ed
    Port:          <none>
    Host Port:     <none>
    Args:
      echo
      Nautobot Initialization Done
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    4
      Started:      Tue, 06 Jun 2023 09:26:28 -0700
      Finished:     Tue, 06 Jun 2023 09:26:52 -0700
    Ready:          False
    Restart Count:  13
    Limits:
      cpu:     600m
      memory:  8704M
    Requests:
      cpu:     100m
      memory:  1280M
    Environment Variables from:
      nautobot-env           ConfigMap  Optional: false
      nautobot-env           Secret     Optional: false
      mesa-nautobot-secrets  Secret     Optional: false
    Environment:
      NAUTOBOT_UWSGI_BUFFER_SIZE:  8192
    Mounts:
      /opt/nautobot/git from git-repos (rw)
      /opt/nautobot/static from nautobot-static (rw)
      /opt/nautobot/uwsgi.ini from nautobot-config (rw,path="uwsgi.ini")
Containers:
  nautobot:
    Container ID:  
    Image:         ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
    Image ID:      
    Ports:         8443/TCP, 8080/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      nautobot-server
      start
      --ini
      /opt/nautobot/uwsgi.ini
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     600m
      memory:  8704M
    Requests:
      cpu:      100m
      memory:   1280M
    Liveness:   http-get http://:http/api/ delay=3s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/health/ delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment Variables from:
      nautobot-env           ConfigMap  Optional: false
      nautobot-env           Secret     Optional: false
      mesa-nautobot-secrets  Secret     Optional: false
    Environment:
      NAUTOBOT_K8S_COMPONENT:                              nautobot-default
      NAUTOBOT_UWSGI_BUFFER_SIZE:                          8192
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          kdev
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        mesa-dev-nautobot (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              nautobot-default-7b85d4d888-9pf7c (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        nautobot
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10
      NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME:       nautobot-default
    Mounts:
      /opt/nautobot/git from git-repos (rw)
      /opt/nautobot/static from nautobot-static (rw)
      /opt/nautobot/uwsgi.ini from nautobot-config (rw,path="uwsgi.ini")
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nautobot-static:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  git-repos:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  nautobot-config:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        nautobot-config
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  51m                   default-scheduler  Successfully assigned mesa-dev-nautobot/nautobot-default-7b85d4d888-9pf7c to kdev-compute-1
  Normal   Pulled     46m (x5 over 51m)     kubelet            Container image "ghcr.io/nautobot/nautobot:v2.0.0-alpha.3-py3.10" already present on machine
  Normal   Created    46m (x5 over 51m)     kubelet            Created container nautobot-init
  Normal   Started    46m (x5 over 51m)     kubelet            Started container nautobot-init
  Warning  BackOff    102s (x196 over 48m)  kubelet            Back-off restarting failed container
```

JSON excerpt of Volumes/VolumeMounts from k9s while it's in operation.

```
          volumeMounts:
            - mountPath: /opt/nautobot/static
              name: nautobot-static
            - mountPath: /opt/nautobot/git
              name: git-repos
            - mountPath: /opt/nautobot/uwsgi.ini
              name: nautobot-config
              subPath: uwsgi.ini
      [...]
      volumes:
        - emptyDir: {}
          name: nautobot-static
        - emptyDir: {}
          name: git-repos
        - configMap:
            defaultMode: 420
            name: nautobot-config
          name: nautobot-config
```

#### findmnt output

![image](https://github.com/nautobot/helm-charts/assets/101161539/12afeaed-0343-4625-9a77-4782f45d02dd)

## Provided Values

```
nautobot:
  image:
    registry: "ghcr.io"
    repository: "nautobot/nautobot"
    tag: "v2.0.0-alpha.3-py3.10"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "1280M"
    limits:
      cpu: "600m"
      memory: "8704M"
  extraEnvVars:
  - name: NAUTOBOT_UWSGI_BUFFER_SIZE
    value: "8192"
  extraEnvVarsSecret:
  - mesa-nautobot-secrets

  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  
  db:
    host: postgres
    name: nautobot
    user: nautobot
    existingSecret: mesa-nautobot-secrets
    existingSecretPasswordKey: postgres-password
  
  redis:
    existingSecret: mesa-nautobot-secrets
    existingSecretPasswordKey: redis_password

  logLevel: "INFO"
  metrics: true

  superUser:
    enabled: true
    email: "<redacted>"
  
  podSecurityContext:
    enabled: false
  
  containerSecurityContext:
    enabled: false

postgresql:
  enabled: true
  image:
    pullPolicy: "IfNotPresent"
  auth:
    username: nautobot
    database: nautobot
    existingSecret: mesa-nautobot-secrets
    secretKeys:
      userPasswordKey: postgres-password

redis:
  enabled: true
  image:
    pullPolicy: "IfNotPresent"
  auth:
    existingSecret: mesa-nautobot-secrets
    existingSecretPasswordKey: redis_password

celery:
  enabled: false
  replicaCount: 1

ingress:
  enabled: true
  pathType: "Prefix"
  hostname: <redacted>
  ingressClassName: "public-web"
  path: "/"
  annotations:
    cert-manager.io/cluster-issuer: "incommon-ecc"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600s"
    nginx.ingress.kubernetes.io/send_timeout: "600s"
  backendProtocol: "http"
  tls: true
  secretName: "nautobot-tls"

metrics:
  enabled: false

mariadb:
  enabled: false
```

**Comment by slbyrnes1** [comment]
I was able to fix this locally by adding an additional init container to move the uwsgi ConfigMap.

Added:
```
[...]
initContainers:
        {{- if (and (not $.Values.nautobot.singleInit) (or $nautobot.initNautobot $nautobot.staticFilesOnly)) }}
        # Workaround for RO configmap
        - name: prepare-config
          image: busybox:1.36.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: "nautobot-config"
            mountPath: "/mnt/uwsgi.ini"
            subPath: "uwsgi.ini"
          args:
            - "/bin/sh"
            - "-c"
            - "mkdir -p /opt/nautobot && cp /mnt/uwsgi.ini /opt/nautobot/uwsgi.ini"
        # This init container will run post_upgrade which initializes/upgrades the DB as well as collects static files
        - name: nautobot-init
          image: {{ include "nautobot.image" $ }}
         [...]
```

Then I removed the following volumeMount from the "nautobot-init" init container.

```
- name: "nautobot-config"
   mountPath: "/opt/nautobot/uwsgi.ini"
   subPath: "uwsgi.ini"
```

**Comment by slbyrnes1** [comment]
Hrm... maybe not quite. My augmented NAUTOBOT_UWSGI_BUFFER_SIZE env of 8192 is not being passed into the uwsgi.ini configuration as expected; buffer-size is still 4096 when running `cat /opt/nautobot/uwsgi.ini` after initialization. This may totally be user-error... still looking :)

**Comment by nniehoff** [comment]
@slbyrnes1 Thanks for ALL of the detail in this issue there's a lot here, sorry I missed this earlier.  Can you tell me what you are trying to accomplish?  And provide the values you are using to get these errors?

**Comment by slbyrnes1** [comment]
Thanks so much for the response 🙂 

As dictated by the gods of "I've stared at this too much", I validated that I _am_ able to deploy the helm chart just fine without my "hack", so long as I only specify .Values.uWSGIini and _not_ an envVar for NAUTOBOT_UWSGI_BUFFER_SIZE. Hooray for a night's sleep!

That aside, I am still able to recreate my original issue, summarized below. 

**Goal**: Deploy Nautobot with an augmented buffer-size for uwsgi. Our k8s stack is such that the default is too small.

**Log output**:

```
[...]
nautobot-init ?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
nautobot-init 
nautobot-init System check identified 4 issues (0 silenced).
nautobot-init 💡 Superuser Username: admin, E-Mail: nautobot-help@internet2.edu
nautobot-init sed: cannot rename /opt/nautobot/sedkFOxBF: Device or resource busy
Stream closed EOF for mesa-nonworking/nautobot-nonworking-default-688794f897-kdr8v (nautobot-init)
```

**Invocation**:

```
% kubectl create namespace mesa-nonworking
kubectl apply -f .testing-secret.yml -n mesa-nonworking
helm install nautobot-nonworking nautobot/nautobot --namespace mesa-nonworking --create-namespace --values=./values/nonworking-values.yml
```

**Values.yml**:

```
nautobot:
  image:
    registry: "ghcr.io"
    repository: "nautobot/nautobot"
    tag: "v2.0.0-beta.1-py3.10"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "1280M"
    limits:
      cpu: "600m"
      memory: "8704M"
  extraEnvVars:
  - name: NAUTOBOT_UWSGI_BUFFER_SIZE
    value: "8192"
  extraEnvVarsSecret:
  - mesa-nautobot-secrets
  
  db:
    host: postgres
    name: nautobot
    user: nautobot
    existingSecret: mesa-nautobot-secrets
    existingSecretPasswordKey: postgres-password
  
  redis:
    existingSecret: mesa-nautobot-secrets
    existingSecretPasswordKey: redis_password

  logLevel: "INFO"
  metrics: true

  superUser:
    enabled: true
    email: "nautobot-help@internet2.edu"
  
postgresql:
  enabled: true
  image:
    pullPolicy: "IfNotPresent"
  auth:
    username: nautobot
    database: nautobot
    existingSecret: mesa-nautobot-secrets
    secretKeys:
      userPasswordKey: postgres-password

redis:
  enabled: true
  image:
    pullPolicy: "IfNotPresent"
  auth:
    enabled: false

celery:
  enabled: false
  replicaCount: 1

ingress:
  enabled: true
  pathType: "Prefix"
  ingressClassName: "public-web"
  path: "/"
  annotations:
    cert-manager.io/cluster-issuer: "incommon-ecc"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600s"
    nginx.ingress.kubernetes.io/send_timeout: "600s"
  backendProtocol: "http"
  tls: true
  secretName: "nautobot-tls"

metrics:
  enabled: false

mariadb:
  enabled: false

```

#### Some Additional Information

**K3S Version**: v.1.23

This is my theory, which may be garbage: Because NAUTOBOT_UWSGI_BUFFER_SIZE is specified, [this line](https://github.com/nautobot/nautobot/blob/eee2eaa2420caedb080c8225126ceb12b5e3ecba/docker/docker-entrypoint.sh#L92) is being called in Nautobot's docker-entrypoint where it is trying to modify uwsgi.ini.

However, it breaks, as the uwsgi.ini configmap is mounted as read-only, despite what `kubectl describe pod` may say:

```
nautobot@nautobot-nonworking-default-688794f897-wz4dn:~$ findmnt --real
TARGET                 SOURCE                                                                                                                                                            FSTYPE OPTIONS
/dev/termination-log   /dev/sda4[/var/lib/kubelet/pods/108b1367-1338-4d33-8bac-af5abf9b9cdd/containers/nautobot-init/e04800f9]                                                           xfs    rw,rela
/etc/resolv.conf       /dev/sda4[/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri/sandboxes/fce585d3a4123c49e7684647842706048dbde830f4a62df56ea1a312f99029f1/resolv.conf] xfs    rw,rela
/etc/hosts             /dev/sda4[/var/lib/kubelet/pods/108b1367-1338-4d33-8bac-af5abf9b9cdd/etc-hosts]                                                                                   xfs    rw,rela
/etc/hostname          /dev/sda4[/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri/sandboxes/fce585d3a4123c49e7684647842706048dbde830f4a62df56ea1a312f99029f1/hostname]    xfs    rw,rela
/opt/nautobot/uwsgi.ini
                       /dev/sda4[/var/lib/kubelet/pods/108b1367-1338-4d33-8bac-af5abf9b9cdd/volumes/kubernetes.io~configmap/nautobot-config/..2023_06_09_22_38_46.1396084715/uwsgi.ini]  xfs    ro,rela
/opt/nautobot/static   /dev/sda4[/var/lib/kubelet/pods/108b1367-1338-4d33-8bac-af5abf9b9cdd/volumes/kubernetes.io~empty-dir/nautobot-static]                                             xfs    rw,rela
/opt/nautobot/git      /dev/sda4[/var/lib/kubelet/pods/108b1367-1338-4d33-8bac-af5abf9b9cdd/volumes/kubernetes.io~empty-dir/git-repos]  
```

Based on this older k8s issue, ConfigMap mounts being RO is intentional: https://github.com/kubernetes/kubernetes/issues/62099
