### ISSUE TITLE
Bug: variable celery.concurrency not used

### ISSUE THREAD

**Issue by BlackDark** [nautobot/helm-charts#286]
The variable you define in the values: https://github.com/nautobot/helm-charts/blob/develop/charts/nautobot/values.yaml#L456 is not used in any template therefore not used.
This is heavy in kubernetes environment where the nodes can be beefy machines and the default preforking orientated on available core counts and not assigned memory therefore the baseline memory consumption can be incredibly high without any load.

As a workaround:
- you can modify the `command`
- or add the `args` for the worker:
```yml
workers:
  default:
    # concurrency: 2 # not working in the helm chart -> BUG
    args:
      - --concurrency
      - "2"
    # Not sure what the best bet is. Maybe slightly less than 200M memory per concurrency on idle and 500M on load?
    resources:
      requests:
        cpu: "100m"
        memory: "350M"
      limits:
        cpu: "1000m"
        memory: "1G"
```
