### ISSUE TITLE
Installing with postgresql & redis enabled with password is broken in the `2.1.0`

### ISSUE THREAD

**Issue by gertzakis** [nautobot/helm-charts#375]
Installing a release with postgresql & redis enabled that are not using pre-existing secrets causes nautobot pod to fail with `Error: secret "release-name-nautobot-postgresql" not found` .

Meaning I have a values file like:
```
postgresql:
  enabled: true
  auth:
    password: "nautobot"
redis:
  enabled: true
  auth:
    password: "nautobot"
```
but the Nautobot pods are failing that they cannot find those secrets.

The reason being that the names of the secrets and the ones that the deployment is configured to use are different.
Specifically, after some tshoot the pods are configured to use fullname-nautobot-postgresql & nautobot-redis, but the secrets have names fullname-postgresql & fullname-redis respectively.
