### ISSUE TITLE
Enable S3 Storage Backend

### ISSUE THREAD

**Issue by sabinayakc** [nautobot/helm-charts#487]
Using this helm chart, what's the best way to enable the s3 storage backend.

I have my config as follow

```
STORAGE_BACKEND = "storages.backends.s3.S3Storage"

STORAGE_CONFIG = {
    "AWS_ACCESS_KEY_ID": "...",
    "AWS_SECRET_ACCESS_KEY": "...",
    "AWS_STORAGE_BUCKET_NAME": "my-bucket-name",
    "AWS_S3_REGION_NAME": "us-west-1",
    "AWS_DEFAULT_ACL": "public-read",
    "AWS_QUERYSTRING_AUTH": False,
    "AWS_LOCATION": "subfolder/name/static/"
}
JOB_FILE_IO_STORAGE = STORAGE_BACKEND
STATICFILES_STORAGE = STORAGE_BACKEND
```
And have created the bucket.

However, I am getting the following error during init. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/storages/backends/s3.py", line 35, in <module>
    import boto3.session
ModuleNotFoundError: No module named 'boto3'

During handling of the above exception, another exception occurred:
```

Looks I need to do a pip install using an init container ? 

```
$ echo "nautobot[remote_storage]" >> $NAUTOBOT_ROOT/local_requirements.txt
$ pip3 install "nautobot[remote_storage]" boto3
```

**Comment by ubajze** [comment]
@sabinayakc  thank you for opening an issue. The issue is that the boto3 is not installed in the base Nautobot image. The proper way to resolve your issue is to build a new image containing all the requirements and use the Nautobot base image as a source. This image must be published in a Docker repository. If this is a private repository, provide the secrets required to pull the image.

Then you will have to add additional settings in the values:
```
# Nautobot Server
nautobot:
  image:
    registry: "<your docker registry>"  # for example, ghcr.io
    repository: "<your docker repository>". # for example, nautobot-project/nautobot
    tag: "<your image tag>". # for example v2.3.13
```
