### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by asergeant01** [nautobot/helm-charts#8]
In order to support plugins within containerised deployments, a user should have 2 options:
1) Use their own infrastructure to rebuild the nautobot container including their plugins
2) Have their plugin loaded into the default nautobot container before execution

Option 1 is currently available to users and requires no further development from this side, however option 2 is not currently available and requires further discussion on viability and implementation.

You can consider a Pod to be a self-contained, isolated "logical host" that contains the systemic needs of the application it serves. You describe a desired state in a Deployment which will orchestrate pods/containers to meet that state declaration. Deployments should be idempotent and therefore installing dependencies at runtime  is not recommended.

I believe a possible solution to this is to build containers with simply the plugin code and its associated dependencies. This would achieve a versioned, idempotent container,  that could be run to pre-populate a shared volume with the nautobot container.

To give an example / idea - consider a plugin build using the following Dockerfile and the nautobot chart deployed using the following values:

```
FROM my_repo/alpine:latest

# Install Pip to be able to resolve dependencies
RUN apk add py3-pip

# Make Directories
RUN mkdir /my_plugin/
RUN mkdir /my_plugin/app
RUN mkdir /my_plugin/dependencies

WORKDIR /my_plugin/

# Copy App from local filesystem to container
COPY . /my_plugin/app

# Download pip requirements into container for offline install
RUN pip download /my_plugin/app -d /my_plugin/dependencies

# Assume /plugins will be a PV mounted to the this container & make dirs within it
RUN mkdir /plugins
RUN mkdir /plugins/nautobot-plugin-awx-jobs
RUN mkdir /plugins/nautobot-plugin-awx-jobs-dependencies

# Copy this plugins versioned code and dependencies to the PV
CMD cp -R /my_plugin/app /plugins/nautobot-plugin-awx-jobs && cp -R /my_plugin/dependencies /plugins/nautobot-plugin-awx-jobs-dependencies
```

```
nautobot:
  extraVolumes:
    - name: nautobot-plugins
      emptyDir: {}

  extraVolumeMounts:
    - name: nautobot-plugins
      mountPath: /plugins

  initContainers:
    - name: nautobot-plugin-awx-jobs
      image: artifactory/nautobot-plugin-awx-jobs:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: nautobot-plugins
          mountPath: /plugins
```

When the nautobot container starts, the plugins directory is available to it:

```
nautobot@nautobot-97c7fc76c-4ff7d:/plugins$ ls
nautobot-plugin-awx-jobs  nautobot-plugin-awx-jobs-dependencies
```

What this gives is 2 folders within the main nautobot container that the docker-entrypoint.sh script could look into and install.
